### ISSUE TITLE
JSON Decoding Errors

### ISSUE THREAD

**Issue by drewmarkrose2** [meraki/dns-o-matic#1]
I need some help running this script, I am getting an error when I run this script, and things are getting screwy between DNS-o-Matic and Umbrella. Here is the output

Traceback (most recent call last):
  File "c:\python27\Meraki\update_ip_addr_dns.py", line 46, in <module>
    headers=headers).json() for org in orgs]))
  File "c:\Python27\lib\site-packages\requests\models.py", line 812, in json
    return complexjson.loads(self.text, **kwargs)
  File "c:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "c:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by markp73** [comment]
I also need some help, when first running the script, I got:

>>>
Traceback (most recent call last):
  File "update_ip_addr_dns.py", line 9, in <module>
    import requests
ImportError: No module named requests
>>>

so I installed the requests module. Tried installing 'itertools' and 'sys' as they were under requests in the script. [No idea if I'm doing this right BTW]
Next I run the script, get similar to the above poster:

>>>
Traceback (most recent call last):
  File "update_ip_addr_dns.py", line 91, in <module>
    headers=headers).json() for org in orgs]))
  File "/Library/Python/2.7/site-packages/requests/models.py", line 886, in json
    return complexjson.loads(self.text, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
>>>

**Comment by tmn-m** [comment]
I too have not been able to use this script as I'm getting errors, anyone overcome this yet?

Traceback (most recent call last):
  File "update_ip_addr_dns.py", line 46, in <module>
    headers=headers).json() for org in orgs]))
  File "update_ip_addr_dns.py", line 46, in <listcomp>
    headers=headers).json() for org in orgs]))
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\json\
    return _default_decoder.decode(s)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\json\
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\json\
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
